USE [InventarioUH]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Bodega](
    [id] [int] IDENTITY(1,1) NOT NULL,
      NOT NULL,
      NULL,
PRIMARY KEY CLUSTERED ([id] ASC)
) ON [PRIMARY]
GO